spring:
  decorator:
    datasource:
      p6spy:
        enable-logging: true
        multiline: true
        logging: slf4j
        tracing:
          include-parameter-values: true
      sleuth:
        enabled: true
        include: connection, query, fetch
  application:
    name: TracePG
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tracepg
    username: tracepg
    password: tracepg
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: script.sql
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
server:
  port: 8080